FROM	google/debian:wheezy
RUN     apt-get -y update
RUN     apt-get -y upgrade
RUN	apt-get -y install make gcc build-essential sudo
RUN	apt-get -y install apache2-threaded-dev
RUN	apt-get -y install libapache2-mod-perl2
RUN	apt-get -y install libtest-harness-perl libtap-formatter-junit-perl libjson-perl
RUN	apt-get -y install rpm
